name: Sync Main to Other Branches (Safe Merge)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Safely Merge Main into Other Branches
        run: |
          SOURCE_BRANCH="main"
          TARGETS=("qa" "frontend" "backend" "dev")

          git fetch origin

          for TARGET in "${TARGETS[@]}"; do
            if [ "$SOURCE_BRANCH" == "$TARGET" ]; then
              echo "Skipping $TARGET (same as source)"
              continue
            fi

            echo "Merging $SOURCE_BRANCH into $TARGET"

            # Fetch and checkout the target branch
            git fetch origin $TARGET:$TARGET || true
            git checkout $TARGET
            git pull origin $TARGET

            # Merge dev into target branch
            git merge origin/$SOURCE_BRANCH --no-ff -m "Merge $SOURCE_BRANCH into $TARGET"

            # Push the merged branch
            git push origin $TARGET
          done
