name: Sync Dev to Other Branches

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Sync Dev into Other Branches
        run: |
          SOURCE_BRANCH="dev"
          TARGETS=("qa" "frontend" "backend")

          for TARGET in "${TARGETS[@]}"; do
            if [ "$SOURCE_BRANCH" == "$TARGET" ]; then
              echo "Skipping $TARGET (same as source)"
              continue
            fi

            echo "Syncing changes from $SOURCE_BRANCH into $TARGET"

            # Fetch latest
            git fetch origin

            # Checkout target branch
            git checkout $TARGET
            git pull origin $TARGET

            # Merge dev into target
            git merge origin/$SOURCE_BRANCH -m "Merge $SOURCE_BRANCH into $TARGET" || {
              echo "Merge conflict occurred in $TARGET. Please resolve manually."
              exit 1
            }

            # Push if there are changes
            if [ -n "$(git status --porcelain)" ]; then
              git push origin $TARGET
            else
              echo "No changes to push for $TARGET"
            fi
          done
