name: Run Tests on Dev Push

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make run_tests.sh executable
        run: chmod +x ./run_tests.sh

      - name: Run Tests
        run: ./run_tests.sh
